import { sourceMetrics } from './diagram-metrics.mjs';
import { OF_LIMITS } from './diagram-craft-rules.mjs';

const MAX_EDGE_LABEL_ANCHOR_DISTANCE=24;
const ARROWHEAD_CANVAS_FLOOR=12/1080;
const ARROWHEAD_STROKE_MULTIPLE=5;

const contamination=[
  /\blitfamily\b/i, /\b(?:generator|generated by|template|prototype)\b/i,
  /\bsource\s*:/i, /\bnotes?\s*:/i, /\bstatic\s+first\b/i,
  /\baccessible\s+labels\b/i, /\bone\s+accent\b/i, /\bfocal\b/i,
  /\b(?:light|dark|full)\s*[·|/]\s*static\b/i, /\bdesign\s+rules?\b/i,
  /^\s*show\b/i,
];

import { BOUNDARY_EDGE_PADDING, ARROWHEAD_TARGET_TOLERANCE, attributes, widthOf, visibleSvgText, svgContent, parseRoutes, rectangles, boundaryOutlines, segmentHitsBox, segmentHitsText, textOverlapsNode, gap, routeDistance, isBoundaryLabel, textHitsOutline, segmentAlongOutline, markerDefinitions, markerOverlapsTarget, markerFor, markerScale, markerHeadLength, markerTip, distanceToBoxBoundary, decisionBranchQuality, routeLength, routeBends, routeManhattanDistance, alignedRouteKind, routeCrossesBoundary, collinearOverlap, routeCrossingPoints } from './visual-quality-geometry.mjs';

function officeDiagramChecks(texts, nodes, outlines, viewBox) {
  const issues = [], advisories = [];
  if (outlines.length >= 2) {
    const group = (node) => outlines.filter((outline) => node.x + node.w / 2 >= outline.x && node.x + node.w / 2 <= outline.x + outline.w && node.y + node.h / 2 >= outline.y && node.y + node.h / 2 <= outline.y + outline.h).sort((a,b)=>a.w*a.h-b.w*b.h)[0] ?? 'ungrouped';
    const same = [], different = [];
    for (let i=0;i<nodes.length;i++) for (let j=i+1;j<nodes.length;j++) (group(nodes[i])===group(nodes[j]) ? same : different).push(gap(nodes[i],nodes[j]));
    if (same.length && different.length) {
      const intra = Math.max(...same), inter = Math.min(...different);
      if (intra > 0 && inter < OF_LIMITS.groupGapRatio * intra) issues.push(`OF-201 CLUSTER_GAP_RATIO inter=${inter.toFixed(1)} intra=${intra.toFixed(1)} required=${OF_LIMITS.groupGapRatio}`);
    }
  }
  const hues = [];
  const canvasArea = viewBox ? viewBox.w * viewBox.h : Infinity;
  for (const node of nodes) {
    if (node.display === 'none' || node.w * node.h >= canvasArea * OF_LIMITS.fullBleedFraction) continue;
    const hex = /^#([0-9a-f]{6}|[0-9a-f]{3})$/i.exec(node.fill);
    if (!hex) continue;
    const raw = hex[1].length === 3 ? [...hex[1]].map((digit)=>digit+digit).join('') : hex[1];
    const [r,g,b]=[0,2,4].map((offset)=>parseInt(raw.slice(offset,offset+2),16)/255),high=Math.max(r,g,b),low=Math.min(r,g,b),delta=high-low,lightness=(high+low)/2;
    const saturation = delta === 0 ? 0 : delta / (1-Math.abs(2*lightness-1));
    if (lightness < OF_LIMITS.accentLightnessMin || lightness > OF_LIMITS.accentLightnessMax || saturation < OF_LIMITS.accentSaturationMin) continue;
    const hue = ((high===r?((g-b)/delta)%6:high===g?(b-r)/delta+2:(r-g)/delta+4)*60+360)%360;
    if (!hues.some((prior)=>Math.min(Math.abs(prior-hue),360-Math.abs(prior-hue))<=OF_LIMITS.hueFamilyDegrees)) hues.push(hue);
  }
  if (hues.length >= OF_LIMITS.accentHighFamilies) issues.push(`OF-202 ACCENT_COUNT families=${hues.length} max=${OF_LIMITS.accentHighFamilies-1}`);
  else if (hues.length >= OF_LIMITS.accentMediumFamilies) advisories.push(`OF-202 ACCENT_COUNT families=${hues.length} suggested<=2`);
  for (const text of texts) {
    const chars=[...text.label],latin=chars.filter((char)=>/[A-Za-z0-9]/.test(char)).length/Math.max(1,chars.filter((char)=>/\S/.test(char)).length);
    if (latin >= OF_LIMITS.latinShareMin && text.label !== text.label.toUpperCase()) {
      const words=text.label.match(/[A-Za-z]+/g)??[],long=words.filter((word)=>word.length>=OF_LIMITS.titleCaseWordLength),capitalized=long.filter((word)=>/^[A-Z][a-z]+$/.test(word));
      if (capitalized.length>=OF_LIMITS.titleCaseMinWords && capitalized.length/Math.max(1,long.length)>OF_LIMITS.titleCaseShareMin && words.some((word)=>/^(Of|And|The|To|For|In)$/.test(word))) advisories.push(`OF-203 LABEL_CASE ${text.label}`);
    }
    const box = text.nodeFor ? nodes.find((node)=>node.id===text.nodeFor) : text.boundaryFor ? outlines.find((outline)=>outline.id===text.boundaryFor) : null;
    if (box) {
      const measured = widthOf(text.label,text.size),available=box.w-2*BOUNDARY_EDGE_PADDING;
      if (measured>available) issues.push(`OF-204 LABEL_OVERFLOW ${text.label} width=${measured.toFixed(1)} available=${available.toFixed(1)}`);
    }
  }
  return { issues, advisories };
}

function sequenceQuality(source,svg=svgContent(source),nodes=rectangles(svg),routes=parseRoutes(svg)){
  if(!/\bdata-type\s*=\s*["']sequence(?:-oauth)?["']/i.test(source)&&!/\bid\s*=\s*["']diagram-sequence(?:-oauth)?-[^"']+["']/i.test(svg))return [];
  const lifelines=new Map();
  for(const match of svg.matchAll(/<line\b([^>]*)>/gi)){
    const a=attributes(match[1]),name=a['data-lifeline-for'];
    if(name&&a['stroke-dasharray']&&Number(a.x1)===Number(a.x2)&&Number(a.y2)>Number(a.y1))lifelines.set(name,{x:Number(a.x1),top:Number(a.y1),bottom:Number(a.y2)});
  }
  const issues=[],messages=routes.map((route)=>({route,start:route.segments[0].slice(0,2),end:route.segments.at(-1).slice(2,4),y:(route.segments[0][1]+route.segments.at(-1)[3])/2}));
  const lastMessageY=Math.max(0,...messages.map((message)=>message.y));
  for(const node of nodes){
    const line=lifelines.get(node.id);
    if(!line){issues.push('SEQUENCE_LIFELINE_MISSING '+node.id);continue;}
    if(Math.abs(line.x-(node.x+node.w/2))>1||Math.abs(line.top-(node.y+node.h))>1)issues.push('SEQUENCE_LIFELINE_ALIGNMENT '+node.id);
    if(line.bottom+1<lastMessageY)issues.push('SEQUENCE_LIFELINE_SHORT '+node.id+' ends before last message');
  }
  let previousY=-Infinity;
  for(const message of messages){
    const from=lifelines.get(message.route.from),to=lifelines.get(message.route.to);
    if(!from||!to)continue;
    if(Math.abs(message.start[0]-from.x)>1||Math.abs(message.end[0]-to.x)>1)issues.push('SEQUENCE_MESSAGE_OFF_LIFELINE '+message.route.from+'->'+message.route.to);
    if(message.y<=previousY)issues.push('SEQUENCE_MESSAGE_ORDER '+message.route.from+'->'+message.route.to+' is not top-to-bottom');
    previousY=message.y;
  }
  return issues;
}

function visualQuality(source,{enforceCanvas=false,scale=null}={}){
  const svg=svgContent(source),texts=visibleSvgText(svg),nodes=rectangles(svg),routes=parseRoutes(svg),outlines=boundaryOutlines(svg),markers=markerDefinitions(svg),metrics=sourceMetrics(source),issues=[],advisories=[],sequenceDiagram=/\bdata-type\s*=\s*["']sequence(?:-oauth)?["']/i.test(source);
  const contaminated=texts.filter((t)=>contamination.some((rule)=>rule.test(t.label))).map((t)=>t.label);
  if(contaminated.length)issues.push('PROCESS_TEXT '+[...new Set(contaminated)].join(' | '));
  for(const text of texts.filter((item)=>item.role==='edge'||item.edgeFor)){
    const matches=routes.filter((route)=>route.from+'|'+route.to===text.edgeFor&&(!route.label||route.label===text.label));
    if(!text.edgeFor||matches.length!==1){issues.push('EDGE_LABEL_UNBOUND '+(text.edgeFor||text.label));continue;}
    const own=matches[0],distance=routeDistance(text.anchor,own),nearestOther=Math.min(Infinity,...routes.filter((route)=>route!==own).map((route)=>routeDistance(text.anchor,route)));
    if(distance>MAX_EDGE_LABEL_ANCHOR_DISTANCE)issues.push('EDGE_LABEL_TOO_FAR '+text.label+' own='+distance.toFixed(1)+'px max='+MAX_EDGE_LABEL_ANCHOR_DISTANCE+'px');
    if(Number.isFinite(nearestOther)&&distance>=nearestOther)issues.push('EDGE_LABEL_NEAREST_PATH '+text.label+' own='+distance.toFixed(1)+'px other='+nearestOther.toFixed(1)+'px');
    for(const node of nodes)if(textOverlapsNode(text,node))issues.push('EDGE_LABEL_NODE_COLLISION '+text.label+' overlaps '+node.id);
  }
  for(const route of routes){
    const facing=routeManhattanDistance(route),ratio=facing?routeLength(route)/facing:null,aligned=alignedRouteKind(route,nodes);
    if(ratio>1.4)issues.push('ROUTE_DETOUR '+route.from+'->'+route.to+' ratio='+ratio.toFixed(2)+' max=1.40');
    if(aligned)issues.push('ROUTE_ALIGNED_PATH '+route.from+'->'+route.to+' '+aligned+' neighbors require one straight segment');
    const crossesBoundary=outlines.some((outline)=>routeCrossesBoundary(route,outline)),bendLimit=crossesBoundary?3:2,bends=routeBends(route);
    if(bends>bendLimit)issues.push('ROUTE_BENDS '+route.from+'->'+route.to+' bends='+bends+' max='+bendLimit);
    if(route.markerStart&&route.markerEnd)issues.push('ROUTE_OPPOSED_HEADS '+route.from+'->'+route.to);
    for(const text of texts)for(const segment of route.segments)if(segmentHitsText(segment,text)){issues.push('EDGE_TEXT_COLLISION '+route.from+'->'+route.to+': '+text.label);break;}
    for(const node of nodes)if(node.id!==route.from&&node.id!==route.to&&route.segments.some((s)=>segmentHitsBox(s,node,8)))issues.push('ROUTE_THROUGH_NODE '+route.from+'->'+route.to+' via '+node.id);
    for(const outline of outlines)if(route.segments.some((segment)=>segmentAlongOutline(segment,outline))){issues.push('ROUTE_ALONG_BOUNDARY '+route.from+'->'+route.to+' along '+outline.id);break;}
    const target=nodes.find((node)=>node.id===route.to);
    for(const edge of ['start','end'])if(edge==='end'?route.markerEnd:route.markerStart){
      const marker=markerFor(route,edge,markers),minimum=Math.max(ARROWHEAD_STROKE_MULTIPLE*route.strokeWidth,ARROWHEAD_CANVAS_FLOOR*(metrics.viewBox?.w||1080));
      const length=markerHeadLength(marker)*markerScale(marker||{units:'userSpaceOnUse'},route);
      if(!marker)issues.push('ARROWHEAD_GEOMETRY_MISSING '+route.from+'->'+route.to+' '+edge);
      else if(length+0.01<minimum)issues.push('ARROWHEAD_SIZE_FLOOR '+route.from+'->'+route.to+' '+edge+'='+length.toFixed(1)+'px min='+minimum.toFixed(1)+'px (12/1080 canvas, 5x stroke)');
    }
    if(route.markerEnd&&target&&!sequenceDiagram){
      const marker=markerFor(route,'end',markers),tip=markerTip(route,marker,'end');
      if(tip&&distanceToBoxBoundary(tip,target)>ARROWHEAD_TARGET_TOLERANCE)issues.push('ARROWHEAD_TIP_MISSED_TARGET '+route.from+'->'+route.to+' gap='+distanceToBoxBoundary(tip,target).toFixed(1)+'px max='+ARROWHEAD_TARGET_TOLERANCE+'px');
    }
    if(route.markerEnd&&target&&markerOverlapsTarget(route,target,markers))issues.push('ARROWHEAD_TARGET_OVERLAP '+route.from+'->'+route.to+' marker intersects target '+target.id);
  }
  issues.push(...decisionBranchQuality(nodes,routes));
  for(let i=0;i<routes.length;i++)for(let j=i+1;j<routes.length;j++){
    if(collinearOverlap(routes[i],routes[j]))issues.push('ROUTE_COLLINEAR_OVERLAP '+routes[i].from+'->'+routes[i].to+' / '+routes[j].from+'->'+routes[j].to+' shared within 12px');
    for(const point of routeCrossingPoints(routes[i],routes[j]))issues.push('ROUTE_CROSSING '+routes[i].from+'->'+routes[i].to+' / '+routes[j].from+'->'+routes[j].to+' at '+point[0].toFixed(1)+','+point[1].toFixed(1));
  }
  issues.push(...sequenceQuality(source,svg,nodes,routes));
  for(const text of texts)for(const outline of outlines)if(textHitsOutline(text,outline)){issues.push('OUTLINE_TEXT_COLLISION '+text.label+' crosses '+outline.id);break;}
  const boundaryTexts=texts.filter((text)=>isBoundaryLabel(text,outlines));
  const boundaryContrastFailures=boundaryTexts.filter((text)=>metrics.contrastFailures.some((failure)=>failure.text===text.label));
  for(const text of boundaryContrastFailures)issues.push('BOUNDARY_CONTRAST_FLOOR '+text.label+' below 4.5:1');
  for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++)if(gap(nodes[i],nodes[j])<12)issues.push('NODE_GAP '+nodes[i].id+'/'+nodes[j].id+' below 12px');
  const fontFailures=[];
  if(enforceCanvas){
    const ratio=scale??(metrics.viewBox?Math.min(metrics.viewBox.w/1080,metrics.viewBox.h/640):1);
    if(!texts.some((t)=>t.role==='title'))issues.push('TITLE_ROLE_MISSING visible title must use data-role="title"');
    for(const t of texts){const boundary=isBoundaryLabel(t,outlines),minimum=t.role==='title'?28:t.role==='edge'||boundary?13:t.role==='node'?15:0;if(minimum&&t.size+0.01<minimum*ratio){const failure=(boundary?'boundary':t.role)+':'+t.label+'='+t.size+'px (min '+(minimum*ratio).toFixed(1)+'px)';if(boundary)issues.push('BOUNDARY_FONT_FLOOR '+failure);else fontFailures.push(failure);}}
    if(fontFailures.length)issues.push('FONT_FLOOR '+fontFailures.join(' | '));
    const points=nodes.flatMap((n)=>[[n.x,n.y],[n.x+n.w,n.y+n.h]]).concat(routes.flatMap((r)=>r.segments.flatMap((s)=>[[s[0],s[1]],[s[2],s[3]]])));
    const box=points.reduce((b,p)=>({left:Math.min(b.left,p[0]),top:Math.min(b.top,p[1]),right:Math.max(b.right,p[0]),bottom:Math.max(b.bottom,p[1])}),{left:Infinity,top:Infinity,right:-Infinity,bottom:-Infinity});
    if(nodes.length&&metrics.viewBox){const safeWidth=metrics.viewBox.w*.90,safeHeight=metrics.viewBox.h*.74,width=(box.right-box.left)/safeWidth,height=(box.bottom-box.top)/safeHeight;if(width<.75||height<.54)issues.push('CONTENT_FILL safe-area-width='+width.toFixed(3)+' safe-area-height='+height.toFixed(3)+' minimum=.75/.54');}
    if(!nodes.length)issues.push('CONTENT_NODES_MISSING');
  }
  const office = officeDiagramChecks(texts,nodes,outlines,metrics.viewBox);
  issues.push(...office.issues);
  advisories.push(...office.advisories);
  return {issues,advisories,contaminated,fonts:fontFailures,nodes:nodes.length,edges:routes.length,edgeLabelMaxAnchorDistance:MAX_EDGE_LABEL_ANCHOR_DISTANCE,arrowheadFloor:{canvas:ARROWHEAD_CANVAS_FLOOR,strokeMultiple:ARROWHEAD_STROKE_MULTIPLE,targetTolerance:ARROWHEAD_TARGET_TOLERANCE},boundaryTexts:boundaryTexts.length};
}
export { visualQuality, visibleSvgText, parseRoutes, rectangles, boundaryOutlines, sequenceQuality };
